### ISSUE TITLE
Colors Reference

### ISSUE THREAD

**Issue by maxxxis** [Microsoft/vsts-sample-wit-custom-control#11]
Where do we find the colors reference for specifying colors other than the examples??

**Comment by ostreifel** [comment]
https://github.com/Microsoft/vsts-extension-color-control/blob/e939cfa70de64a8aa30c6141d4be41ff45b9bf0c/scripts/view.ts#L30
Any [css color](https://www.w3schools.com/colors/colors_picker.asp) will work. 
##### Example
```
#ff0000;#00ff00;#0000ff
```

**Comment by maxxxis** [comment]
Sorry it took so long, our suppport team only recently loaded your extension. When I attempt to use the following colors for my Complexity (val: 1-5) & Risk (val: 1-5) fields:              <Control Label="Complexity" Type="LabelControl" />              <ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">                <Inputs>                  <Input Id="FieldName" Value="ARMS.Complexity" />                  <Input Id="Colors" Value="#f7072f,#f79307,#ebf707,#07aff7,#07f7c3" />                </Inputs>              </ControlContribution>              <Control Label="Risk" Type="LabelControl" />              <ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">                <Inputs>                  <Input Id="FieldName" Value="ARMS.Risk" />                  <Input Id="Colors" Value="#f7072f,#f79307,#ebf707,#07aff7,#07f7c3" />                </Inputs>              </ControlContribution>


the colors that display are nowhere near what I'm trying to set. See attached pics.
Thanks,Miguel


    On Tuesday, January 16, 2018, 8:58:14 AM PST, Otto Streifel <notifications@github.com> wrote:  
 
 
https://github.com/Microsoft/vsts-extension-color-control/blob/e939cfa70de64a8aa30c6141d4be41ff45b9bf0c/scripts/view.ts#L30
Any css color will work.

Example
#ff0000;#00ff00;#0000ff

**Comment by ostreifel** [comment]
@maxxxis GitHub seems to have removed your email attachments. Can you attach those files again but through the browser?

**Comment by ostreifel** [comment]
Nvm, I just looked at the xml included again and the root issue is separators - extension is looking for ';' not ','.

ex: color;color;color

**Comment by ostreifel** [comment]
<Control Label="Complexity" Type="LabelControl" />
<ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
    <Inputs>
        <Input Id="FieldName" Value="ARMS.Complexity" />
        <Input Id="Colors" Value="#f7072f;#f79307;#ebf707;#07aff7;#07f7c3" /> </Inputs>
</ControlContribution>
<Control Label="Risk" Type="LabelControl" />
<ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
    <Inputs>
        <Input Id="FieldName" Value="ARMS.Risk" />
        <Input Id="Colors" Value="#f7072f;#f79307;#ebf707;#07aff7;#07f7c3" /> </Inputs>
</ControlContribution>

**Comment by ostreifel** [comment]
```
<Control Label="Complexity" Type="LabelControl" />
<ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
    <Inputs>
        <Input Id="FieldName" Value="ARMS.Complexity" />
        <Input Id="Colors" Value="#f7072f;#f79307;#ebf707;#07aff7;#07f7c3" /> </Inputs>
</ControlContribution>
<Control Label="Risk" Type="LabelControl" />
<ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
    <Inputs>
        <Input Id="FieldName" Value="ARMS.Risk" />
        <Input Id="Colors" Value="#f7072f;#f79307;#ebf707;#07aff7;#07f7c3" /> </Inputs>
</ControlContribution>
```

**Comment by maxxxis** [comment]
ostreifel, thanks for the quick response. I changed the semicolons to commas, but it did not change anything from my first report, i.e. the colors were the same as the previous screenshots.

              <Control Label="Complexity" Type="LabelControl" />
              <ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
                <Inputs>
                  <Input Id="FieldName" Value="ARMS.Complexity" />
                  <Input Id="Colors" Value="DARKRED,CORAL,GOLD,LightSkyBlue,PALEGREEN" />
                </Inputs>
              </ControlContribution>
              <Control Label="Risk" Type="LabelControl" />
              <ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
                <Inputs>
                  <Input Id="FieldName" Value="ARMS.Risk" />
                  <Input Id="Colors" Value="#f7072f,#f79307,#ebf707,#07aff7,#07f7c3" />
                </Inputs>
              </ControlContribution>
![2018-01-30 17_24_54-features](https://user-images.githubusercontent.com/28545851/35641346-d4cd20e2-0674-11e8-8e46-eefd8565ea6d.png)
![2018-01-30 17_24_25-features](https://user-images.githubusercontent.com/28545851/35641347-d4e9be46-0674-11e8-9828-1aef59393a5b.png)

**Comment by ostreifel** [comment]
@maxxxis No they need to BE semicolons, they were originally commas in the code that you pasted and I changed  to semicolons in my code sample.
