### ISSUE TITLE
COLOR PICKER IGNORING SPECIFIED LIST COLORS 

### ISSUE THREAD

**Issue by maxxxis** [Microsoft/vsts-sample-wit-custom-control#12]
I have two integer lists for complexity & risk with values that range 1-5.
Regardless of color values I specify, either via HTML name or hex, the color picker is choosing its own colors which are the same for each of these controls.

              <Control Label="Complexity" Type="LabelControl" />
              <ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
                <Inputs>
                  <Input Id="FieldName" Value="ARMS.Complexity" />
                  <Input Id="Colors" Value="#f7072f,#f79307,#ebf707,#07aff7,#07f7c3" />
                </Inputs>
              </ControlContribution>
              <Control Label="Risk" Type="LabelControl" />
              <ControlContribution Label=" " Id="ms-devlabs.color-form-control.color-control-contribution">
                <Inputs>
                  <Input Id="FieldName" Value="ARMS.Risk" />
                  <Input Id="Colors" Value="#f7072f,#f79307,#ebf707,#07aff7,#07f7c3" />
                </Inputs>
              </ControlContribution>
Results in:
![2018-01-30 17_24_54-features](https://user-images.githubusercontent.com/28545851/35601211-ae062ec4-05e6-11e8-95cd-0c027fa42766.png)
![2018-01-30 17_24_25-features](https://user-images.githubusercontent.com/28545851/35601212-ae28128c-05e6-11e8-990d-27e87292e22e.png)

TIA!

**Comment by mmanela** [comment]
Try using ; instead of , to separate the color values.

**Comment by shayki5** [comment]
I have the same issue, I can't choose my own colors. (I tried also using ; instead of ,) .

**Comment by mmanela** [comment]
@shayki5  Can you share your config?

/cc @ostreifel  @mohitbagra

**Comment by shayki5** [comment]
@mmanela I tried this:
`<ControlContribution Label="Priority" Id="ms-devlabs.color-form-control.color-control contribution">`
               `<Inputs>`
                 `<Input Id="FieldName" Value="MyCompnay.ResolutionPriority" />`
                  `<Input Id="Colors" Value="#f7075f,#f7071f,#f7081f,#f7091f" />`
                `</Inputs>`
              `</ControlContribution>`

ans this:
`<ControlContribution Label="Priority" Id="ms-devlabs.color-form-control.color-control-contribution">`
                `<Inputs>`
                 ` <Input Id="FieldName" Value="MyCompnay.ResolutionPriority" />`
                  `<Input Id="Colors" Value="#f7075f;#f7071f;#f7081f;#f7091f" />`
                `</Inputs>`
              `</ControlContribution>`

**Comment by ostreifel** [comment]
Configuring on vsts

![image](https://user-images.githubusercontent.com/5203542/38632567-f973b594-3d71-11e8-96f5-54b28617acef.png)
Running on vsts
![image](https://user-images.githubusercontent.com/5203542/38632578-02657002-3d72-11e8-9800-616f6ae7baef.png)

Configuraton on tfs17u2
![image](https://user-images.githubusercontent.com/5203542/38634153-8e718488-3d76-11e8-9ee4-35f9ec1f4c6c.png)



Running on tfs17u2
![image](https://user-images.githubusercontent.com/5203542/38633967-0ddfeb98-3d76-11e8-8815-8f23d2cb1de3.png)


What environment are you running on? Is there anything that would make your setup unique?

**Comment by shayki5** [comment]
Hi @ostreifel, thank you for your replay!
We using TFS 2017.3, and now it's working :)
Thank you!
