### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by ToddBeaulieu** [Microsoft/vsts-sample-wit-custom-control#15]
Hello, I'm quite new to VS Code, NPM and typescript projects, so I'm stumbling my way through this. I spent a couple of hours trying to get this to build. I got a lot of warnings about out of date packages, so I updated the versions in package.json.

It would be fantastic if someone could nudge me in the right direction.

`grunt package-dev
Running "ts:build" (ts) task
Compiling...
Using tsc v2.9.2
node_modules/@types/jquery/index.d.ts(33,14): error TS2300: Duplicate identifier 'jQuery'.
node_modules/@types/jquery/index.d.ts(40,15): error TS2451: Cannot redeclare block-scoped variable 'jQuery'.
node_modules/@types/jquery/index.d.ts(41,15): error TS2451: Cannot redeclare block-scoped variable '$'.
node_modules/@types/jquery/index.d.ts(51,5): error TS2717: Subsequent property declarations must have the same type.  Property 'ajaxSettings' must be of type 'JQueryAjaxSettings', but here has type 'AjaxSettings<any>'.
node_modules/@types/jquery/index.d.ts(61,5): error TS2717: Subsequent property declarations must have the same type.  Property 'Deferred' must be of type '<T>(beforeStart?: (deferred: JQueryDeferred<T>) => any) => JQueryDeferred<T>', but here has type 'DeferredStatic'.
node_modules/@types/jquery/index.d.ts(62,5): error TS2717: Subsequent property declarations must have the same type.  Property 'Event' must be of type 'JQueryEventConstructor', but here has type 'EventStatic'.
node_modules/@types/jquery/index.d.ts(71,5): error TS2717: Subsequent property declarations must have the same type.  Property 'cssHooks' must be of type '{ [key: string]: any; }', but here has type 'PlainObject<CSSHook<HTMLElement>>'.
node_modules/@types/jquery/index.d.ts(79,5): error TS2717: Subsequent property declarations must have the same type.  Property 'cssNumber' must be of type 'any', but here has type 'PlainObject<boolean>'.
node_modules/@types/jquery/index.d.ts(81,14): error TS2687: All declarations of 'fn' must have identical modifiers.
node_modules/@types/jquery/index.d.ts(81,14): error TS2717: Subsequent property declarations must have the same type.  Property 'fn' must be of type 'any', but here has type 'JQuery<HTMLElement>'.
node_modules/@types/jquery/index.d.ts(82,5): error TS2717: Subsequent property declarations must have the same type.  Property 'fx' must be of type '{ tick: () => void; interval: number; stop: () => void; speeds: { slow: number; fast: number; }; ...', but here has type '{ interval: number; off: boolean; step: PlainObject<AnimationHook<Node>>; }'.
node_modules/@types/jquery/index.d.ts(229,5): error TS2717: Subsequent property declarations must have the same type.  Property 'support' must be of type 'JQuerySupport', but here has type 'PlainObject<any>'.
node_modules/@types/jquery/index.d.ts(6183,5): error TS2300: Duplicate identifier 'param'.
node_modules/@types/jquery/index.d.ts(55666,5): error TS2375: Duplicate number index signature.
node_modules/@types/jquery/index.d.ts(62411,5): error TS2374: Duplicate string index signature.
node_modules/@types/knockout/index.d.ts(237,5): error TS2717: Subsequent property declarations must have the same type.  Property 'init' must be of type '(element: any, valueAccessor: () => any, allBindingsAccessor?: KnockoutAllBindingsAccessor, viewM...', but here has type '(element: E, valueAccessor: () => V, allBindingsAccessor: KnockoutAllBindingsAccessor, viewModel:...'.
node_modules/@types/knockout/index.d.ts(238,5): error TS2717: Subsequent property declarations must have the same type.  Property 'update' must be of type '(element: any, valueAccessor: () => any, allBindingsAccessor?: KnockoutAllBindingsAccessor, viewM...', but here has type '(element: E, valueAccessor: () => V, allBindingsAccessor: KnockoutAllBindingsAccessor, viewModel:...'.
node_modules/@types/knockout/index.d.ts(245,5): error TS2374: Duplicate string index signature.
node_modules/@types/knockout/index.d.ts(322,5): error TS2717: Subsequent property declarations must have the same type.  Property 'domData' must be of type '{ get(node: Element, key: string): any; set(node: Element, key: string, value: any): void; getAll...', but here has type '{ get(node: Node, key: string): any; set(node: Node, key: string, value: any): void; getAll(node:...'.
node_modules/@types/knockout/index.d.ts(336,5): error TS2717: Subsequent property declarations must have the same type.  Property 'domNodeDisposal' must be of type '{ addDisposeCallback(node: Element, callback: Function): void; removeDisposeCallback(node: Elemen...', but here has type '{ addDisposeCallback(node: Node, callback: Function): void; removeDisposeCallback(node: Node, cal...'.
node_modules/@types/knockout/index.d.ts(421,5): error TS2717: Subsequent property declarations must have the same type.  Property 'status' must be of type 'string', but here has type '"added" | "deleted" | "retained"'.
node_modules/@types/knockout/index.d.ts(662,5): error TS2717: Subsequent property declarations must have the same type.  Property 'selectExtensions' must be of type '{ readValue(element: HTMLElement): any; writeValue(element: HTMLElement, value: any): void; }', but here has type '{ readValue(element: HTMLElement): any; writeValue(element: HTMLElement, value: any, allowUnset?:...'.
node_modules/@types/knockout/index.d.ts(784,14): error TS2300: Duplicate identifier 'ko'.
node_modules/@types/node/index.d.ts(243,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
node_modules/@types/node/index.d.ts(815,38): error TS2304: Cannot find name 'Set'.
node_modules/@types/node/index.d.ts(7170,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/react/index.d.ts(27,22): error TS2307: Cannot find module 'csstype'.
node_modules/@types/requirejs/index.d.ts(38,11): error TS2300: Duplicate identifier 'mod'.
node_modules/@types/requirejs/index.d.ts(100,2): error TS2717: Subsequent property declarations must have the same type.  Property 'shim' must be of type '{ [key: string]: RequireShim; }', but here has type '{ [key: string]: string[] | RequireShim; }'.
node_modules/@types/requirejs/index.d.ts(215,2): error TS2717: Subsequent property declarations must have the same type.  Property 'urlArgs' must be of type 'string', but here has type 'string | ((id: string, url: string) => string)'.
scripts/app.ts(32,1): error TS2304: Cannot find name 'VSS'.
scripts/app.ts(32,14): error TS2304: Cannot find name 'VSS'.
scripts/control.ts(51,24): error TS2304: Cannot find name 'VSS'.
scripts/control.ts(57,21): error TS2345: Argument of type 'Promise<Object>[]' is not assignable to parameter of type 'IPromise<any>[]'.
  Type 'Promise<Object>' is not assignable to type 'IPromise<any>'.
    Types of property 'then' are incompatible.
      Type '<TResult1 = Object, TResult2 = never>(onfulfilled?: (value: Object) => TResult1 | PromiseLike<TRe...' is not assignable to type '<U>(onFulfill?: (value: any) => U | IPromise<U>, onReject?: (error: any) => U | IPromise<U>) => I...'.
        Types of parameters 'onfulfilled' and 'onFulfill' are incompatible.
          Type 'U | IPromise<U>' is not assignable to type 'U | PromiseLike<U>'.
            Type 'IPromise<U>' is not assignable to type 'U | PromiseLike<U>'.
              Type 'IPromise<U>' is not assignable to type 'PromiseLike<U>'.
                Types of property 'then' are incompatible.
                  Type '<U>(onFulfill?: (value: U) => U | IPromise<U>, onReject?: (error: any) => U | IPromise<U>) => IPr...' is not assignable to type '<TResult1 = U, TResult2 = never>(onfulfilled?: (value: U) => TResult1 | PromiseLike<TResult1>, on...'.
                    Types of parameters 'onFulfill' and 'onfulfilled' are incompatible.
                      Type 'TResult1 | PromiseLike<TResult1>' is not assignable to type 'TResult2 | IPromise<TResult2>'.
                        Type 'TResult1' is not assignable to type 'TResult2 | IPromise<TResult2>'.
                          Type 'TResult1' is not assignable to type 'IPromise<TResult2>'.
scripts/control.ts(113,9): error TS2304: Cannot find name 'VSS'.
typings/globals/jquery/index.d.ts(3,11): error TS2430: Interface 'JQueryAjaxSettings' incorrectly extends interface 'AjaxSettings<any>'.
  Types of property 'beforeSend' are incompatible.
    Type '(jqXHR: JQueryXHR, settings: JQueryAjaxSettings) => any' is not assignable to type '(this: any, jqXHR: jqXHR<any>, settings: AjaxSettings<any>) => false | void'.
      Types of parameters 'jqXHR' and 'jqXHR' are incompatible.
        Type 'jqXHR<any>' is not assignable to type 'JQueryXHR'.
          Property 'error' is missing in type 'jqXHR<any>'.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'always' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'catch' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'done' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'fail' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'pipe' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'progress' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'JQueryPromise<any>' and 'jqXHR<any>'.
  Named property 'state' of types 'JQueryPromise<any>' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(147,11): error TS2320: Interface 'JQueryXHR' cannot simultaneously extend types 'XMLHttpRequest' and 'jqXHR<any>'.
  Named property 'responseXML' of types 'XMLHttpRequest' and 'jqXHR<any>' are not identical.
typings/globals/jquery/index.d.ts(175,11): error TS2430: Interface 'JQueryCallback' incorrectly extends interface 'Callbacks<Function>'.
  Types of property 'add' are incompatible.
    Type '{ (callbacks: Function): JQueryCallback; (callbacks: Function[]): JQueryCallback; }' is not assignable to type '(callback: TypeOrArray<Function>, ...callbacks: TypeOrArray<Function>[]) => this'.
      Type 'JQueryCallback' is not assignable to type 'this'.
typings/globals/jquery/index.d.ts(290,11): error TS2320: Interface 'JQueryPromise<T>' cannot simultaneously extend types 'JQueryGenericPromise<T>' and 'Promise<T, any, any>'.
  Named property 'then' of types 'JQueryGenericPromise<T>' and 'Promise<T, any, any>' are not identical.
typings/globals/jquery/index.d.ts(330,11): error TS2320: Interface 'JQueryDeferred<T>' cannot simultaneously extend types 'JQueryGenericPromise<T>' and 'Deferred<T, any, any>'.
  Named property 'then' of types 'JQueryGenericPromise<T>' and 'Deferred<T, any, any>' are not identical.
typings/globals/jquery/index.d.ts(541,11): error TS2430: Interface 'JQueryAnimationOptions' incorrectly extends interface 'EffectsOptions<Element>'.
  Types of property 'complete' are incompatible.
    Type 'Function' is not assignable to type '(this: Element) => void'.
      Type 'Function' provides no match for the signature '(this: Element): void'.
typings/globals/jquery/index.d.ts(689,5): error TS2300: Duplicate identifier 'param'.
typings/globals/jquery/index.d.ts(936,5): error TS2687: All declarations of 'fn' must have identical modifiers.
typings/globals/jquery/index.d.ts(3214,14): error TS2300: Duplicate identifier 'jQuery'.
typings/globals/jquery/index.d.ts(3216,13): error TS2451: Cannot redeclare block-scoped variable 'jQuery'.
typings/globals/jquery/index.d.ts(3217,13): error TS2451: Cannot redeclare block-scoped variable '$'.
typings/globals/knockout/index.d.ts(671,11): error TS2300: Duplicate identifier 'ko'.
typings/globals/require/index.d.ts(9,11): error TS2300: Duplicate identifier 'export='.
typings/globals/require/index.d.ts(9,11): error TS2300: Duplicate identifier 'mod'.

>> 56 non-emit-preventing type warnings
>> Error: tsc return code: 2
Warning: Task "ts:build" failed. Use --force to continue.

Aborted due to warnings.`

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
