### ISSUE TITLE
I couldn't work in on-premise

### ISSUE THREAD

**Issue by fthkucuk** [Microsoft/vsts-sample-wit-custom-control#17]
Hi,

I am using Azure DevOps Server 2019 but I couldn't work with this extension.

            <Group Label="Details">
              <ControlContribution Id="ms-devlabs.color-form-control" Label="Priority" >
                <Inputs>
                    <Input Id="FieldName" Value="Microsoft.VSTS.Common.Priority" />
                </Inputs>
            </ControlContribution>

error message
The 'Id' attribute is invalid - The value 'ms-devlabs.color-form-control' is invalid according to its datatype 'http://schemas.microsoft.com/VisualStudio/2008/workitemtracking/typedef:ContributionIdType' - The Pattern constraint failed.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.

[Product Backlog Item.txt](https://github.com/Microsoft/vsts-extension-color-control/files/3023101/Product.Backlog.Item.txt)
![Capture](https://user-images.githubusercontent.com/46280608/55240063-0fa3e400-5249-11e9-875e-0a9172473388.PNG)

**Comment by mmanela** [comment]
I think you are using the wrong id there. The id should be like this

`Id="ms-devlabs.color-form-control.color-control-contribution"`

**Comment by fthkucuk** [comment]
> I think you are using the wrong id there. The id should be like this
> 
> `Id="ms-devlabs.color-form-control.color-control-contribution"`

thank you Matthew :)
