### ISSUE TITLE
i want to create custom control for two way binding

### ISSUE THREAD

**Issue by harieligeti** [Microsoft/vsts-sample-wit-custom-control#18]
could you please explain the complete step by step process for creating a custom control for a workitem type

**Comment by mmanela** [comment]
What do you mean? Are you asking how to write a new control from scratch or to use this one?

**Comment by harieligeti** [comment]
yeah  am asking how to write a new control from scratch??

**Comment by mmanela** [comment]
You can read more about building custom work item form extensions at the following links
* https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-workitem-extension?view=azure-devops
* https://docs.microsoft.com/en-us/azure/devops/extend/develop/custom-control?view=azure-devops
