### ISSUE TITLE
Unable to build node_modules/@types/node/base.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type must be of type 'Require', but here has type 'NodeRequire'.

### ISSUE THREAD

**Issue by dasmeter** [Microsoft/vsts-sample-wit-custom-control#19]
When running grunt package-dev I'm getting the following error -

node_modules/@types/node/base.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type must be of type 'Require', but here has type 'NodeRequire'.

Steps to duplicate: 

1. Import project cloned/downloaded from git hub into VS Code
https://github.com/microsoft/vsts-extension-color-control

2. Open Terminal in VS Code - cd C:\extensions\vsts-sample-wit-custom-control
3. Run npm install to install required local dependencies.
4. Run npm install -g grunt to install a global copy of grunt (unless it's already installed).

5. Run grunt package-dev.

Getting the error:

node_modules/@types/node/base.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type must be of type 'Require', but here has type 'NodeRequire'.

I was having several compile errors until I run through the following -

npm uninstall -g typescript@2.9.2
npm i typescript@2.1.4
npm install typings --global
typings install --global dt~es6-shim
then I added to tsconfig.json - "lib": ["es2015", "dom"] to compilerOptions . 
npm install @types/lodash@4.14.108 --save-exact
npm i -D @types/lodash@ts2.3

Now I'm just dealing with the error above - any help would be appreciated.  Using Visual Studio Code.

Thanks

**Comment by dasmeter** [comment]
Does anyone have any ideas?

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
