### ISSUE TITLE
[object Object] displayed instead of list options

### ISSUE THREAD

**Issue by CassandraReitzQA** [Microsoft/vsts-sample-wit-custom-control#21]
We use the color control plugin for our Priority field in Azure DevOps. On occasion, instead of listing out the four priority options, we get a javascript looking error that says [object Object]:

![image](https://user-images.githubusercontent.com/45465289/61654046-3d41ec80-ac81-11e9-9304-14cd64907544.png)

Our color names and definitions are the following:

![image](https://user-images.githubusercontent.com/45465289/61654221-914cd100-ac81-11e9-81a7-45734f903f63.png)

The error appears intermittently, usually when creating a new work item that hasn't been saved yet.

**Comment by Racarson** [comment]
We are having the exact same issue.  Please let me know when there is a resolution.  Thanks.

**Comment by adamtha** [comment]
Had the same issue, added a new picklist on the same page and now both fields appear correctly

![image](https://user-images.githubusercontent.com/7962362/61711689-4b653b00-ad5d-11e9-9b27-3418e38c0f77.png)

**Comment by Racarson** [comment]
I tried that yesterday and it didn't work.  I believe the issue is intermittent and it still an issue today.

**Comment by obvioussean** [comment]
This was a bug that was recently introduced unrelated to the extension.  A mitigation has been applied and the issue should no longer be happening, as long as you reload the browser window.  If you still see it, please reactivate this issue.
