### ISSUE TITLE
backing field does not have allowed values

### ISSUE THREAD

**Issue by estacado** [Microsoft/vsts-sample-wit-custom-control#23]
Hi,

I try to create a selection for the business value, but if i update my work item i have this message :
"The backing field doest not have allowed values, for more information click here"

I follow the screenshot on the business value from this : https://marketplace.visualstudio.com/items?itemName=ms-devlabs.color-form-control&ssr=false#overview
But i haven't the same behavior that the priority field :/ 

With the priority field i can put a list of values, but with business value no...

i made a mistake somewhere ?

PS: sorry for my bad english

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
