### ISSUE TITLE
Unable to remove selection

### ISSUE THREAD

**Issue by blwillia** [Microsoft/vsts-sample-wit-custom-control#24]
We have the extension implemented and for the most part we like it.  However, we often delete the value for the field and leave it empty.  That is a specific indicator for us that it needs to be addressed later.  With the Color Control, we have no way of 'unpicking' an option.

Expected behavior:
![image](https://user-images.githubusercontent.com/2389006/80529960-ec70ca00-895d-11ea-9617-06ded1469b2b.png)
If we click on a field that is already selected, we want it to be unselected.  Leaving no options selected. The backing field should be empty and nothing should be selected like below.
![image](https://user-images.githubusercontent.com/2389006/80530123-2a6dee00-895e-11ea-82e5-7ddb32452e6f.png)

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
