### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by twahl0630** [Microsoft/vsts-sample-wit-custom-control#26]
The colors are not showing up on the card on the Kapan board.  I just see the name of the pic list, not the color that it was assigned to.  So when adding in the field on the tile in the Kapan board there is no visual of color just the physical name. that it was selected. Also, there is no way to clear it out. We are trying to use this as a flagging option.

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
