### ISSUE TITLE
color-form-control by ms-devlabs is taking longer than expected to load.

### ISSUE THREAD

**Issue by lotharchris** [Microsoft/vsts-sample-wit-custom-control#27]
I am a user of TFS, and when I view any page that has color-form-control by ms-devlabs, I get a warning:
"color-form-control by ms-devlabs is taking longer than expected to load."

It never loads.

this was working two days ago.
Nothing on my machine/browser has changed.
Nothing to my knowledge has been changed on server side.
Cleared browser cache, no help.
Rebooted browser machine, no help.

Any direction is appreciated.

![image](https://user-images.githubusercontent.com/60582861/118832275-7c95f000-b88e-11eb-9888-40ed827b0164.png)

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
