### ISSUE TITLE
error while trying to upload extension to market : "The stated category 'Plan and track' is no longer supported."

### ISSUE THREAD

**Issue by eysidisi** [Microsoft/vsts-sample-wit-custom-control#28]
**Problem:** When I try to upload extension to official marketplace it gives an error saying that "The stated category 'Plan and track' is no longer supported" and doesn't accept package

**Solution:** Edit "vss-extension.json" file and replace 

"categories": [
        "Plan and track"
    ],

with one of the valid values namely: Azure Repos, Azure Boards, Azure Pipelines, Azure Test Plans, and Azure Artifacts. 
Source: https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops

**Comment by AminTi** [comment]
Thanks for reporting.

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
