### ISSUE TITLE
Colour names/definitions

### ISSUE THREAD

**Issue by darshanrampatel** [Microsoft/vsts-sample-wit-custom-control#7]
I was wondering which set of colour names is defined for this control?

I am trying to work out the best colours to use but not sure what all of the options are or where they are defined.

Ideally, I'd like to know the names of the below colours (from the query charts):
![image](https://cloud.githubusercontent.com/assets/14162899/20300818/c297e942-ab18-11e6-82c7-e6f6945cd55a.png)

**Comment by cschleiden** [comment]
These are the default colors:

```
["darkred", "red", "orange", "yellow", "blue", "darkblue", "purple"]
```

You can pass in any valid CSS color, some examples: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

**Comment by darshanrampatel** [comment]
@cschleiden, thanks - I didn't even think to try CSS colours!
