### ISSUE TITLE
Enhancement Request: Show colours on queries

### ISSUE THREAD

**Issue by darshanrampatel** [Microsoft/vsts-sample-wit-custom-control#8]
Not sure if this is possible, but it would be great to be able to show the colours on the query view, similar to State:

![image](https://cloud.githubusercontent.com/assets/14162899/20301389/06b23036-ab1b-11e6-8805-e0bccf6ee220.png)

**Comment by nicksimons-limeade** [comment]
+1 This would be great!

**Comment by MOlausson** [comment]
Sorry, but this code in this repo is not currently being maintained.
